#!/bin/bash
# Day 4, part 2
# Indiana Jones stares at the swordsman, takes out the gun and BAM!
cut -f 3,4 input.calculated |
while read i j; do
    seq $i $j | head -n-1
done |
awk '{min[$1]++}END{for(k in min){if(min[k]>mc){mc=min[k];mk=k}} print mk}' > most-popular-min
read min < most-popular-min

cut -f 1,3,4 input.calculated |
while read id i j; do
    [ $min -ge $i -a $min -lt $j ] && echo $id
done |
    awk '{id[$1]++}END{for(k in id) if(id[k]>mc){mc=id[k];mk=k} print substr(mk,2)}' > guard
read guard < guard
expr $min \* $guard
