#!/bin/bash
# Prepare
rm data.sqlite
sqlite3 data.sqlite 'CREATE TABLE fabric (elf VARCHAR, x INT, y INT)'

# Load data
time ./tosqlite.pl input | sqlite3 data.sqlite '.import /dev/stdin fabric'

# sqlite did all:
time sqlite3 data.sqlite 'SELECT count(1) FROM (SELECT x, y FROM fabric GROUP BY x, y HAVING count(1) > 1)'

# Output: 101469
