/*
 * check-fast
 * program for The Advent of Code 2018
 * Reads data from stdin generated by:
 *      join -j 2 input input | awk '$1!=$2'
 * (cartesian product, minus diagonal)
 * Will check for "string proximity" as described for Day 2, part 2.
 */
#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[])
{
    char a[27] = {0}, b[27] = {0}, result[27] = {0}, *p, *q, *r = result;
    while (scanf(" %s %s\n", a, b) == 2) {
        for (p = a, q = b; *p == *q; p++, q++) {
            *r = *p;
            r++;
        }
        for (p += 1, q += 1; *p == *q; p++, q++) {
            *r = *p;
            r++;
        }
        if(strlen(result) == 25)
            puts(result);
        memset(result, 0, sizeof result);
        r = result;
    }
    return 0;
}
