#!/bin/bash

# All of them match 2 chars.
grep -Pc '(.).*\1' input

# 29 have 3 chars
perl -ne 's/(^.*)(.)(.*)\2(.*)\2(.*$)/$1$3$4$5/g && print' input | wc -l 
# TODO: find better regex

# Of the 3 chars, after removing them, how many matches for 2 chars? -> 28
perl -ne 's/(^.*)(.)(.*)\2(.*)\2(.*$)/$1$3$4$5/g && print' input | grep -Pc '(.).*\1'

# Only one has 3 chars, but no 2 chars, then the checksum is:
echo $((249*29))
